baseURL = 'https://aauy.essucalgary.com'
languageCode = 'en-us'
title = 'Ask An Upper Year'
theme = "ananke"

DefaultContentLanguage = "en"

[params]
  site_logo = "/images/banner.png"
  custom_css = ["custom.css"]
  cover_dimming_class = "cover-bg-red"
  background_color_class = "bg-white"

[languages]
  [languages.en]
    title = "AAUY"
    weight = 1
    contentDir = "content/en"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About Us"
        url = "/about/single/"
        weight = 2
    [[menu.main]]
        name = "Question Blog"
        url = "/faq/"
        weight = 3
    [[menu.main]]
        name = "Contact Us"
        url = "/contact/"
        weight = 4